# Determines if we search the title (optional). Defaults to true.
matchTitle: true

# Determines if we search the body (optional). Defaults to true.
matchBody: true

# Determines if label matching is case sensitive (optional). Defaults to true.
caseSensitive: false

# Explicit keyword mappings to labels. Form of match:label. Required.
labelMappings:
  Audio : Audio
  Video : Video
  Documentation : Documentation
  Android Dev (Flutter): Android-Dev-Flutter
  Android Dev (Kotlin): Android-Dev-Kotlin
  Android Dev (Java): Android-Dev-Java
  Backend Dev (Java):  Backend-Dev-Java
  Backend Dev (.NET):  .NET
  Backend Dev (PHP):  Backend-Dev-PHP
  Backend Dev (Python): Backend-Dev-Python
  C/CPP : C/CPP
  Competitive Programming : Competitive Programming
  Cyber Security : Cyber Security
  DSA : DSA
  Database : Database
  Datascience with Python : DSWP
  Datascience with R : Datascience with R
  Frontend Dev HTML/CSS/JS : Frontend Dev HTML/CSS/JS
  Frontend Dev React/Angular/Vue : Frontend Dev React/Angular/Vue
  Golang : Golang
  Interview Prep : Interview Prep
  Java_Domain : Java
  JavaScript : JavaScript
  MERN : MERN
  Machine Learning : Machine Learning
  Open Source : Open Source
  Python_Domain : Python
  Rust : Rust
  Statistics : Statistics
  UI/UX : UI/UX
