# Determines if we search the title (optional). Defaults to true.
matchTitle: true

# Determines if we search the body (optional). Defaults to true.
matchBody: true

# Determines if label matching is case sensitive (optional). Defaults to true.
caseSensitive: false

# Explicit keyword mappings to labels. Form of match:label. Required.
labelMappings:
  Audio : Audio
  Video : Video
  Documentation : Documentation
  Android Dev : Android Dev
  Backend Dev :  Backend Dev
  C/CPP : C/CPP
  Competitive Programming : Competitive Programming
  Cyber Security : Cyber Security
  DSA : DSA
  Database : Database
  Datascience with Python : Datascience with Python
  Datascience with R : Datascience with R
  Frontend Dev HTML/CSS/JS : Frontend Dev HTML/CSS/JS
  Frontend Dev React/Angular/Vue : Frontend Dev React/Angular/Vue
  Golang : Golang
  Interview Prep : Interview Prep
  Java_Domain : Java
  JavaScript : JavaScript
  MERN : MERN
  Machine Learning : Machine Learning
  Open Source : Open Source
  Python_Domain : Python
  Rust : Rust
  Statistics : Statistics
  UI/UX : UI/UX
