# Determines if we search the title (optional). Defaults to true.
matchTitle: true

# Determines if we search the body (optional). Defaults to true.
matchBody: true

# Determines if label matching is case sensitive (optional). Defaults to true.
caseSensitive: false

# Explicit keyword mappings to labels. Form of match:label. Required.
labelMappings:
  Audio : Audio
  Video : Video
  Documentation : Documentation
  Android Dev (Flutter, Java, Kotlin) : Android Dev (Flutter, Java, Kotlin)
  Backend Dev (Java, .NET, Python) :  Backend Dev (Java, .NET, Python)
  C/CPP : C/CPP
  Competitive Programming : Competitive Programming
  Cyber Security : Cyber Security
  DSA : DSA
  Database : Database
  Datascience with Python : Datascience with Python
  Datascience with R : Datascience with R
  Frontend Dev (HTML, CSS, JS) : Frontend Dev (HTML, CSS, JS)
  Frontend Dev (React, Angular, Vue) : Frontend Dev (React, Angular, Vue)
  Golang : Golang
  Interview Prep : Interview Prep
  Java : Java
  JavaScript : JavaScript
  MERN : MERN
  Machine Learning : Machine Learning
  Open Source : Open Source
  Python : Python
  Rust : Rust
  Statistics : Statistics
  UI/UX : UI/UX
  Batch (1) : Batch 1
  Batch (2) : Batch 2
  Batch (3) : Batch 3
  Batch (4) : Batch 4
  Batch (5) : Batch 5
  Batch (6) : Batch 6
  Batch (7) : Batch 7
  Batch (8) : Batch 8
  Batch (9) : Batch 9
  Batch (10) : Batch 10
  Batch (11) : Batch 11
  Batch (12) : Batch 12
  Batch (13) : Batch 13
  Batch (14) : Batch 14
  Batch (15) : Batch 15
  Batch (16) : Batch 16
  Batch (17) : Batch 17
  Batch (18) : Batch 18
  Batch (19) : Batch 19
  Batch (20) : Batch 20
