# -*- coding: utf-8 -*-
"""Python: Concepts-List comprehension.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YPboRcZwYmo_BjUhKxRm5pGCiUBMT7Wq

**Introduction**

List comprehension allows us to write a code in shorter and better way, when we need to create a new list based on the existing list. 
It's a truly pythonic way of coding. Less code and more effectiveness.

Let us understand with an example:

Suppose if you want to create a list of numbers which are divisible by 3 from 1 to 10000 and wrote the following code..
"""

# Creating a new list
my_list= []
#Iterating through the list 
for i in range(1,10000):
  if i%3==0: # checking if the value of i is divisible by 3 
    my_list.append(i) # if the condition satisfies the value will be appended to the list
print(my_list)

"""There is nothing wrong with the above code but what if I say that we can write the same in single line?

Let us understand how:
"""

my_list1 = [i for i in range(1,10000) if i%3==0]
print(my_list1)

"""This is how **List Comprehension** makes everything simple and easy.They are even faster than a for loop which is very useful.

Now we will try to understand the **Syntax** of Lists Comprehension:

**list = [expression for item in iterable if condition == true]**

The return value is a new list, leaving the old list unchanged.

**Condition**

It accepts only the elements which satisfies the condition.

Example:
"""

my_list3 = [16,13,24,12,22,18,13]
eligibity = [age for age in my_list3 if age>=18]
print(eligibity)

"""Condition is optional and can be excluded.

Example:
"""

my_list2 = [ i for i in range(100)]
print(my_list2)

"""**Iterable**

Iterable is a sequence of data that you can iterate over using a loop. 
We use **range()** function to create an iterable.

Lets look at an example:
"""

# program to find out even numbers from 0 to 100
 my_list4=[i for i in range(0,100) if i%2==0]
 print(my_list4)

"""**Expression**

It is current element in the iteration and also the outcome.

Here is an other example:
"""

# Program to find out number of spaces in a given string using list comprehension

string = input() 
my_list5 = list(string)
my_list6=[i for i in my_list4 if i == ' ']
print(len(my_list6))

""" Now that we know all the basics of lists comprehension we will try to solve few problems."""

# Problem 1: Set all the values in the list to upper case
my_list7 = ['Sravani','Revanth','Srija','Kowshika']
my_list8 = [i.upper() for i in my_list7] # 
print(my_list8)

#Remove all the vowels in the given string
 string= input()
 my_list9= list(string)
 my_list10= "".join([i for i in my_list9 if i not in ['a','e','i','o','u']])
 print(my_list10)

#Find all the words in a string that are less than 5 letters

string = input()
my_list11 = string.split(" ")
my_list12 =" ".join( [i for i in my_list11 if len(i)<5])
print(my_list12)