#+TITLE: Windows


** Installing rustup on Windows
+ On Windows, go to https://www.rust-lang.org/tools/install and follow the instructions for installing Rust. At some point in the installation, you’ll receive a message explaining that you’ll also need the C++ build tools for Visual Studio 2013 or later.
+ The easiest way to acquire the build tools is to install Build Tools for Visual Studio 2019. When asked which workloads to install make sure "C++ build tools" is selected and that the Windows 10 SDK and the English language pack components are included.
+ The rest of this book uses commands that work in both cmd.exe and PowerShell. If there are specific differences, we’ll explain which to use.

** Updating and Uninstalling
+ common for all OS.

+ After you’ve installed Rust via =rustup=, updating to the latest version is easy. From your shell, run the following update script:

#+begin_src bash
$ rustup update
#+end_src

+ To uninstall Rust and =rustup=, run the following uninstall script from your shell:

#+begin_src bash
$ rustup self uninstall
#+end_src
