name: Mark Stale Issues and Pull Requests
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            Please reopen this issue once you add more information and updates here.
          stale-pr-message: >
            Please reopen this pull request once you commit the changes requested
            or make improvements on the code.Thank you for your contributions!
          stale-issue-label: "no-issue-activity"
          stale-pr-label: "no-pr-activity"
